name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: 1.22 }
      - uses: actions-rs/toolchain@v1
        with: { toolchain: stable }
      - run: make all
      - run: make windows-agent
